#ACF
```{r}
acf_neyan = acf(neyan$Total.ST.min, plot = TRUE, main="ACF of Daily Total Screen Time (neyan)")
acf_eawerner = acf(eawerner$Total.ST.min, plot = TRUE, main="ACF of Daily Total Screen Time (eawerner)")
acf_vikbala = acf(vikbala$Total.ST.min, plot = TRUE, main="ACF of Daily Total Screen Time (vikbala)")
print(acf_neyan)
print(acf_eawerner)
print(acf_vikbala)
```

#Federated Learning Linear Model
#Setting up packages and functions (shared functions code for each team member)
```{r}
library(readxl)
library(dplyr)

XTX <- function(Y,X){
  return(t(X) %*% X)
}
XTY <- function(Y,X){
  return(t(X) %*% Y)
}

RSS <- function(Y, X, beta) {
  residuals <- Y - X %*% beta
  return(t(residuals) %*% residuals)
}
```

#Getting XTX and XTY From neyan
```{r}
neyan <- read_excel("VENTURE_baseline_data.xlsx", sheet="neyan_data")
X_neyan <- as.matrix(cbind(1, neyan$Pickups, neyan$Num.Classes, neyan$DPSST))
Y_neyan <- as.matrix(neyan$Total.ST.min)
XTX_neyan <- XTX(Y_neyan, X_neyan)
XTY_neyan <- XTY(Y_neyan, X_neyan)
```

#Getting XTX and XTY From vikbala
```{r}
vikbala <- read_excel("VENTURE_baseline_data.xlsx", sheet="vikbala_data")
X_vikbala <- as.matrix(cbind(1, vikbala$Pickups, vikbala$Num.Classes, vikbala$DPSST))
Y_vikbala <- as.matrix(vikbala$Total.ST.min)
XTX_vikbala <- XTX(Y_vikbala, X_vikbala)
XTY_vikbala <- XTY(Y_vikbala, X_vikbala)
```

#Getting XTX and XTY From eawerner
```{r}
eawerner <- read_excel("VENTURE_baseline_data.xlsx", sheet="eawerner_data")
X_eawerner <- as.matrix(cbind(1, eawerner$Pickups, eawerner$Num.Classes, eawerner$DPSST))
Y_eawerner <- as.matrix(eawerner$Total.ST.min)
XTX_eawerner <- XTX(Y_eawerner, X_eawerner)
XTY_eawerner <- XTY(Y_eawerner, X_eawerner)

```

#Global Computing Beta Coefficients
```{r}
# Using shared XTX and XTY matrices from three members
XTX_global <- XTX_neyan + XTX_vikbala + XTX_eawerner
XTY_global <- XTY_neyan + XTY_vikbala + XTY_eawerner
beta_global <- as.numeric(solve(XTX_global) %*% XTY_global)
coef_names <- c("(Intercept)", "Pickups", "Num.Classes", "Hrs.Classes")
names(beta_global) <- coef_names
print(beta_global)
```

```{r}
# Using the global beta and three mean screen time values we got
mean_globalY <- mean(c(mean(Y_neyan), mean(Y_vikbala), mean(Y_eawerner)))


RSS_neyan <- RSS(Y_neyan, X_neyan, beta_global)
TSS_neyan <- sum((Y_neyan - mean_globalY)^2)

RSS_vikbala <- RSS(Y_vikbala, X_vikbala, beta_global)
TSS_vikbala <- sum((Y_vikbala - mean_globalY)^2)

RSS_eawerner <- RSS(Y_eawerner, X_eawerner, beta_global)
TSS_eawerner <- sum((Y_eawerner - mean_globalY)^2)

RSS_global <- RSS_neyan + RSS_vikbala + RSS_eawerner
TSS_global <- TSS_neyan + TSS_vikbala + TSS_eawerner

n <- 42*3
p <- 4
regression_variance_global <- as.numeric(RSS_global / (n - p))
var_cov_matrix_global <- regression_variance_global * solve(XTX_global)
standard_errors_global <- sqrt(diag(var_cov_matrix_global))
R_squared_global <- 1 - (RSS_global / TSS_global)

print(standard_errors_global)
print(R_squared_global)
```

#Original Linear Model
```{r}
combined_data <- read_excel("VENTURE_baseline_data.xlsx", sheet="combined_raw_data")
mod <- lm(Total.ST.min ~ Pickups + Num.Classes + DPSST, data = combined_data)
summary(mod)
```

#Assumption Test
```{r}
library(car)
plot(mod)
vif(mod)
```




